name: PR
on:
  pull_request:
    branches-ignore:
      - 'release-please**'

env:
  NODE_VERSION: '16'
  PNPM_VERSION: 8

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    if: contains(fromJson('["ved-bot", "renovate[bot]"]'), github.actor) == false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get pnpm store directory
        id: pnpm-store-path
        shell: bash
        run: |
          echo "pnpm_store_path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Retrieve pnpm modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-store-path.outputs.pnpm_store_path }}
          key: install-${{ env.NODE_VERSION }}-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            install-${{ env.NODE_VERSION }}-${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: |
            - recursive: false

      - name: Test and Coverage (PR)
        uses: anuraag016/Jest-Coverage-Diff@master
        with:
          accessToken: '${{ secrets.GH_BOT_TOKEN }}'
          runCommand: 'pnpm run test --coverage'
          # delta: 0.5 # Delta of % changed that would make this job fail
          afterSwitchCommand: 'pnpm i'
        env:
          COV_REPORTER: 'json-summary'
          COV_DIRECTORY: './'
