name: CD

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  release:
    name: Release Please
    runs-on: ubuntu-latest

    if: github.event_name != 'workflow_dispatch'

    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release-please
        with:
          token: '${{ secrets.GH_BOT_TOKEN }}'
          command: manifest
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

      # - name: Publish Workflow
      #   if: github.event_name == 'workflow_dispatch' || steps.release-please.outputs.releases_created
      #   env:
      #     GITHUB_TOKEN: '${{ secrets.GH_BOT_TOKEN }}'
      #   run: |
      #     gh workflow run publish.yml

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: [release]

    if: github.event_name == 'workflow_dispatch' || needs.release.outputs.releases_created

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get git HEAD sha
        id: commit-vars
        run: |
          echo ::set-output name=git_head_sha::"$(git rev-parse HEAD)"

      - name: Retrieve pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: install-${{ env.NODE_VERSION }}-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            install-${{ env.NODE_VERSION }}-${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Comment on published commit
        uses: peter-evans/commit-comment@v2
        with:
          token: '${{ secrets.GH_BOT_TOKEN }}'
          sha: '${{ steps.commit-vars.outputs.git_head_sha }}'
          body: |
            🤖 This commit was published to NPM!
